export * from "./dobat-saf/service/dobat-saf.service";
export * from "./mohafza/service/mohafza.service";
export * from "./markaz/service/markaz.service";
export * from "./fea/service/fea.service";
export * from "./daraga/service/daraga.service";
export * from "./qualification/service/qualification.service";
export * from "./selah/service/selah.service";
export * from "./wehda/service/wehda.service";
export * from "./jobTitle/service/job-title.service";
export * from "./promotion/service/promotion.service";
export * from "./efficiency-reports/service/efficency-reports.service"
export * from "./crime-type/service/crime-type.service";
export * from "./crime-sanction/service/crime-sanction.service";
export * from "./sanction/service/sanction.service"
export * from "./vacation/service/vacation.service";
export * from "./mission/service/mission.service";
export * from "./transportation/service/transportation.service";
export * from "./role/service/role.service";
export * from "./user/service/user.service";
export * from "./fea_class/service/fea-class.service";