export * from "./dobat-saf/model/dobatSaf.model";
export * from "./mohafza/model/mohafza.model";
export * from "./markaz/model/markaz.model";
export * from "./fea/model/fea.model";
export * from "./daraga/model/daraga.model";
export * from "./qualification/model/qualification.model";
export * from "./selah/model/selah.model";
export * from "./wehda/model/wehda.model";
export * from "./jobTitle/model/jobTitle.model";
export * from "./khedmaStatus/model/index.model";
export * from "./promotion/model/promotion.model";
export * from "./efficiency-reports/model/efficiencyReports.model"
export * from "./crime-type/model/crimeType.model";
export * from "./crime-sanction/model/crimeSanction.model"
